# Generated by Django 4.2.2 on 2023-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.CharField( max_length=30),
            preserve_default=False,
        ),
    ]
