# Generated by Django 4.2.2 on 2023-07-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Categories',
            field=models.ManyToManyField(to='courses.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
